[env]
framework = arduino
monitor_speed = 115200
lib_deps =
    mikem/RadioHead
    bblanchon/ArduinoJson
    adafruit/Adafruit seesaw Library
    adafruit/Adafruit MAX1704X
    adafruit/Adafruit LTR390 Library
    adafruit/Adafruit SHT4x Library
    adafruit/Adafruit SGP40 Sensor
    adafruit/Adafruit INA237 and INA238 Library

[env:feather_m0]
platform = atmelsam
board = adafruit_feather_m0
build_flags = -D BOARD_FEATHER_M0

[env:pico2w]
platform = raspberrypi
board = rpipico2w
board_build.core = earlephilhower
build_flags = -D BOARD_PICO

; [env:pico2]
; platform = raspberrypi
; board = rpipico2
; board_build.core = earlephilhower
; build_flags = -D BOARD_PICO

; [env:picow]
; platform = raspberrypi
; board = rpipicow
; board_build.core = earlephilhower
; build_flags = -D BOARD_PICO

; [env:pico]
; platform = raspberrypi
; board = rpipico
; board_build.core = earlephilhower
; build_flags = -D BOARD_PICO