[env:feather_m0]
platform = atmelsam
board = adafruit_feather_m0
framework = arduino
monitor_speed = 115200
lib_deps =
    mikem/RadioHead
    bblanchon/ArduinoJson
    adafruit/Adafruit seesaw Library
    adafruit/Adafruit MAX1704X
    adafruit/Adafruit LTR390 Library
    adafruit/Adafruit SHT4x Library
    adafruit/Adafruit SGP40 Sensor
    adafruit/Adafruit INA237 and INA238 Library